# https://docs.cert-manager.io/en/latest/tasks/issuing-certificates/ingress-shim.html
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${STATIC_IP}
    cert-manager.io/cluster-issuer: ${CERTIFICATE_ISSUER}
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: ${APP_NAME}
spec:
  tls:
  - hosts:
    - ${DOMAIN}
    secretName: ${SSL_SECRET_NAME}
  rules:
  -
    host: ${DOMAIN}
    http:
      paths:
      - path: /*
        backend:
          serviceName: ${APP_NAME}
          servicePort: ${SERVER_PORT}